version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-test-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017   
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
      - "5173:5173"
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend 
  
volumes:
  mongo-test-data:
